### ISSUE TITLE
How to build/compile/use Linux?

### ISSUE THREAD

**Issue by cnlohr** [8051Enthusiast/at51#6]
I've tried both downloading the application, to which I get:

```
./at51: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./at51)
```

And git cloning but can't find instructions to build.  How can I use this tool?

**Comment by 8051Enthusiast** [comment]
You can install `cargo` with https://rustup.rs and then install the tool with `cargo install at51`.

I'll have to fix the libc issue; rust uses the system libc by default and it seems like it linked against a fairly new version, so maybe I should compile with musl to have a truly static version.

**Comment by 8051Enthusiast** [comment]
The new release should now contain a truly static build so the libc version problem is hopefully resolved.
I also moved the installation instructions in the README to the front and add a link to rustup.

Please write if there is still a problem.
