### ISSUE TITLE
`Cargo.lock` is not in sync with `Cargo.toml` in the 1.1.0 release

### ISSUE THREAD

**Issue by FFY00** [8051Enthusiast/at51#8]
Hi,

I package at51 for Arch Linux (https://archlinux.org/packages/extra/x86_64/at51/) and when trying to update to 1.1.0 I noticed the `Cargo.lock` file shipped included in the release is not in sync with `Cargo.toml`. This is because commit 152da5331c97e19a29cfa8771c93bfeba6bf91a0 wasn't included in the release.

This is problematic because we use the lockfile for the build, keeping our binaries as close as possible to upstream's, and this also allows us to make the builds reproducible without having to maintain our own `Cargo.lock` file separately. You can read more about this in https://wiki.archlinux.org/title/Rust_package_guidelines.

Would it be possible to push a 1.1.1 release (since rust doesn't have "-post" releases) fixing this?

Cheers,
Filipe

**Comment by 8051Enthusiast** [comment]
Ah sorry for that, I pushed a new 1.1.1 release
